# Generated by Django 2.1.3 on 2018-12-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mass', models.TextField()),
                ('radius', models.TextField()),
                ('period_days', models.FloatField()),
                ('surface_temperature', models.FloatField()),
                ('discovery_year', models.IntegerField()),
                ('distance_from_sun', models.FloatField()),
                ('status', models.TextField()),
            ],
        ),
    ]
