# Generated by Django 2.1.4 on 2018-12-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='discovery_year',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='distance_from_sun',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='planet',
            name='period_days',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planet',
            name='status',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='planet',
            name='surface_temperature',
            field=models.TextField(),
        ),
    ]
